name: Post Build Workflow

run-name: Post Build Workflow -- ${{github.event.repository.name}}

on:
    workflow_dispatch:
    push:
        tags: '**'
jobs:
    post_release_actions:
        name: Post Build Action -- ${{github.ref_name}}
        runs-on: ubuntu-24.04
        if: contains(github.ref_type, 'tag')
        steps:
         - name: IKMDEV Post Build Action
           uses: ikmdev/maven-post-build-action@v3.3.0
           with:
             nexus_repo_url: ${{secrets.NEXUS_URL}}
             nexus_repo_username: ${{secrets.NEXUS_USER}}
             nexus_repo_password: ${{secrets.NEXUS_PASSWORD}}
             branch_name: ${{github.event.workflow_run.head_branch}}
             github_token: ${{secrets.GITHUB_TOKEN}}
             maven_central_username: ${{secrets.MC_SECRET_USERNAME}}
             maven_central_password: ${{secrets.MC_SECRET_PASSWORD}}
             gpg_key: ${{secrets.GPG_KEY}}
             gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
             sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
             sonarcloud_tests: ${{ '' }}
