name: Release Workflow

run-name: "Releasing ${{ github.event.repository.name }} #${{github.run_number}}"

# Trigger workflow manually
on:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}
  TRUNK_BRANCH_NAME: ${{ github.event.repository.default_branch }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'ikmdev'
    steps:
      - name: Verify Branch
        if: env.BRANCH_NAME != env.TRUNK_BRANCH_NAME
        run: |
          echo "ERROR: Attempting to release from branch ${{env.BRANCH_NAME}}. Release from ${{env.TRUNK_BRANCH_NAME}} branch only"
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}
    
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '21'

      - name: Extract Maven GAV
        id: get_gav
        run: |
          echo "GROUP_ID=$(./mvnw help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "ARTIFACT_ID=$(./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "POM_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Setup Git User
        run: |
          git config user.name "ikmdevops"
          git config user.email devops@ikm.dev

      - name: GitFlow Release
        id: gitflow_release
        run: |
          ./mvnw clean install
          ./mvnw ${{steps.get_gav.outputs.GROUP_ID}}:${{steps.get_gav.outputs.ARTIFACT_ID}}:${{steps.get_gav.outputs.POM_VERSION}}:release \
              --batch-mode \
              -DfetchRemote=false \
              -DversionDigitToIncrement=3
