name: Release Workflow

run-name: "Releasing ${{ github.event.repository.name }} #${{github.run_number}}"

# Trigger workflow manually
on:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}
  TRUNK_BRANCH_NAME: ${{ github.event.repository.default_branch }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'ikmdev'
    steps:
      - name: Verify Branch
        if: env.BRANCH_NAME != env.TRUNK_BRANCH_NAME
        run: |
          echo "ERROR: Attempting to release from branch ${{env.BRANCH_NAME}}. Release from ${{env.TRUNK_BRANCH_NAME}} branch only"
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}
    
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '21'

      - name: Extract Version
        id: get_current_version
        run: |
             echo "POM_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
    
      - name: Setup Git User
        run: |
              git config user.name "ikmdevops"
              git config user.email devops@ikm.dev
    
    
      - name: GitFlow Release
        id: gitflow_release
        run: |
              ./mvnw gitflow:release \
                    --batch-mode \
                    -DversionDigitToIncrement=3 \
                    -DpostReleaseGoals="clean install \
                          --batch-mode \
                          -e \
                          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                          -Dmaven.build.cache.enabled=false"
    
      - name: Create Release
        id: create_release
        run: |
              curl -L \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/${{github.repository}}/releases \
              -d '{"tag_name":"${{steps.get_current_version.outputs.POM_VERSION}}","name":"Release ${{steps.get_current_version.outputs.POM_VERSION}}","body":"Release ${{steps.get_current_version.outputs.POM_VERSION}}","draft":false,"prerelease":false,"generate_release_notes":false}'